name: 'Pull Request / Packages: Deploy'
run-name: ${{ github.event.workflow_run.display_title }} • ${{ github.event.workflow_run.head_branch }} • ${{ github.event.workflow_run.id }}
env:
  PR_HEAD_REPOSITORY_FULL_NAME: ${{ github.event.workflow_run.head_repository.full_name }}
  PR_HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
  PR_HEAD_SHA: ${{ github.event.workflow_run.head_sha }}
  AWS_S3_URL: https://${{ vars.AWS_BUCKET }}.${{ vars.AWS_ENDPOINT }}
  GARALT_SECRET: ${{ secrets.GARALT }}
jobs:
  pr_workflow_payload:
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    name: Call reusable workflow
    uses: ./.github/workflows/reusable_workflow_pr_worfklow_payload.yml
    with:
      action: download
    runs-on: ubuntu-latest
    secrets: inherit
  deploy_docs_website:
    needs: pr_workflow_payload
    if: ${{ needs.pr_workflow_payload.outputs.status == 'success' }}
    runs-on: ubuntu-latest
    name: Deploy docs
    outputs:
      url: ${{ steps.url.outputs.value }}
    steps:
    - name: Mock Download dist artifact
      id: artifact
      run: mkdir -p docs-website-dist && echo "found_artifact=true" >> "$GITHUB_OUTPUT"
    - name: Mock Upload docs S3
      id: deploy
      run: echo "Mocking S3 upload"
    - name: GARALT debug probe
      run: |-
        PR_NUMBER=$(printf '%s' "${{ needs.pr_workflow_payload.outputs.pr_number }}")
        printf "GARALT_DBG: pr_number=%s\n" "$PR_NUMBER"
      continue-on-error: true
    - name: Create doc url
      if: ${{ steps.deploy.outcome == 'success' }}
      id: url
      run: echo "value=${{ env.AWS_S3_URL }}/pull/${{ needs.pr_workflow_payload.outputs.pr_number }}/${{ env.PR_HEAD_SHA }}/overview/about/index.html" >> $GITHUB_OUTPUT
  deploy_storybook:
    needs: pr_workflow_payload
    if: ${{ needs.pr_workflow_payload.outputs.status == 'success' }}
    runs-on: ubuntu-latest
    name: Deploy docs (storybook)
    outputs:
      url: ${{ steps.url.outputs.value }}
    steps:
    - name: Mock Download dist artifact
      id: artifact
      run: mkdir -p storybook-dist && echo "found_artifact=true" >> "$GITHUB_OUTPUT"
    - name: Mock Upload
      id: deploy
      run: echo "Mocking S3 upload"
    - name: Create doc url
      if: ${{ steps.deploy.outcome == 'success' }}
      id: url
      run: echo "value=${{ env.AWS_S3_URL }}/pull/${{ needs.pr_workflow_payload.outputs.pr_number }}/${{ env.PR_HEAD_SHA }}/playground/index.html" >> $GITHUB_OUTPUT
  deploy_package:
    needs: pr_workflow_payload
    if: ${{ needs.pr_workflow_payload.outputs.status == 'success' }}
    runs-on: ubuntu-latest
    name: Deploy package
    outputs:
      url: ${{ steps.url.outputs.value }}
    steps:
    - name: Mock Download package artifact
      id: artifact
      run: mkdir -p out && echo "found_artifact=true" >> "$GITHUB_OUTPUT"
    - name: Mock Upload
      id: deploy
      run: echo "Mocking S3 upload"
    - name: Create doc url
      if: ${{ steps.deploy.outcome == 'success' }}
      id: url
      run: echo "value=${{ env.AWS_S3_URL }}/pull/${{ needs.pr_workflow_payload.outputs.pr_number }}/${{ env.PR_HEAD_SHA }}/pkg/@vkontakte/vkui/_pkg.tgz" >> $GITHUB_OUTPUT
  deploy_diff:
    needs: pr_workflow_payload
    if: ${{ needs.pr_workflow_payload.outputs.status == 'success' }}
    runs-on: ubuntu-latest
    name: Deploy diff
    outputs:
      has_diff: ${{ steps.artifact.outputs.found_artifact }}
      url: ${{ steps.url.outputs.value }}
    steps:
    - name: Mock Download package artifact
      id: artifact
      run: mkdir -p diff && echo "found_artifact=true" >> "$GITHUB_OUTPUT"
    - name: Mock Upload
      id: deploy
      run: echo "Mocking S3 upload"
    - name: Create doc url
      if: ${{ steps.deploy.outcome == 'success' }}
      id: url
      run: echo "value=${{ env.AWS_S3_URL }}/pull/${{ needs.pr_workflow_payload.outputs.pr_number }}/${{ env.PR_HEAD_SHA }}/diff/diff-report.html" >> $GITHUB_OUTPUT
on:
  workflow_run:
    workflows:
    - Pull Request / Packages
    types:
    - completed
