name: Reusable workflow / Unit tests
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run unit tests
    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ inputs.ref }}
    - name: Node setup
      uses: ./.github/actions/node-setup
    - name: Mock Run tests
      run: touch test-results.json && mkdir -p .nyc_output && touch .nyc_output/coverage-final.json
    - name: Mock Run tests workspace
      run: echo "Mocking tests"
    - name: Upload test artifact
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: test-output
        path: |
          test-results.json
          .nyc_output/coverage-final.json
env:
  GARALT_SECRET: ${{ secrets.GARALT }}
on:
  workflow_call:
    inputs:
      ref:
        description: The branch, tag or SHA to checkout
        default: ${{ github.ref }}
        required: false
        type: string
      workspace:
        description: Workspace to run tests in (if empty, runs tests for all workspaces)
        required: false
        type: string
